[application]

[web.app]
base_path = "/typepractice/"

# HTML title tag content
title = "typepractice"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "me.bivoje"
publisher = "bivoje"
icon = ["assets/icons/icon.ico"]